//
//  main.c
//  eopsySignal
//
//  Created by Ning on 23/04/2020.
//  Copyright © 2020 Ning. All rights reserved.
//

#include <stdio.h>
#include<stdlib.h>
#include<unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include<signal.h>

#define NUM_CHILD 10

char interrrupt_flag = 0;

void keyBoardInterrupt()
{
    printf(" Parent [%d] : The keyboard interrupt received. \n ", getpid());
    interrrupt_flag = 1;
}

void terminateChildProcess()
{
    printf(" Child [%d] : Termination of the process \n", getpid());
}



int main()
{
    // Create the child process
    
    printf(" Create %d child process \n", NUM_CHILD);
    
    int status = 0;
    int counter = 0;
    
    for(int i = 0; i < NUM_CHILD; i++)
    {
        pid_t pid = fork();
        
        if(pid == 0)
        {
            
        
            /*
             SIGINT
             Generated by Interrupt Key, usually CTRL + C or DELETE. Processes sent to all ForeGround Group
             */
                signal (SIGINT,terminateChildProcess);
                signal (SIGINT,SIG_DFL); // SIG_DFL: This symbol means to restore the system default processing of the signal
          
            printf(" pid : [%d]\n ", pid);
            printf(" This is a child process parent [%d] , the pid id [%d]\n ", getppid(), getpid());
            printf(" Child [%d] start \n", getpid());
            sleep(10);
            printf(" Child [%d] excution has completed \n", getpid());
            exit(0);
            
        }else
        {
            if(pid > 0)
            {
                
                
                    for(int j = 0; j < NSIG; j++) // NSIG : The number of signal which defined
                    {
                        signal(j,SIG_IGN);
                    }
                    signal(SIGCHLD, SIG_DFL);
                    signal(SIGINT, keyBoardInterrupt); // Usually DELETE or CONTROL + C
                
                printf(" pid : [%d]\n ", pid);
                printf(" This is a parent process, the pid id [%d]\n ", getppid());
                
            }else
            {
                printf(" fork() failed \n");
                kill(-1, SIGTERM);
                exit(1);
            }
        }
        sleep(1);
        printf(" One second delays \n\n");
        
        if(interrrupt_flag)
        {
            printf(" Parent [%d] interrupt of creation process \n", getpid());
            kill(pid, SIGTERM);
            break;
        }
        
        
    }
    
    printf(" %d childs process have been created \n", NUM_CHILD);
    
    while(1)
    {
        pid_t child_pid = wait(&status);
        if(child_pid == -1)
        {
            break;
        }else
        {
            counter++;
        }
    }
    
    printf("\n");
    printf(" No more child process\n");
    printf(" %d process terminated ccorrectly\n ", counter);
    
    // Restore the signal
   // #ifdef WITH_SIGNALS
        for(int j=0; j<NSIG;j++)
            signal(j,SIG_DFL);
    //#endif
    
    return 0;
}
